language: ruby
rvm:
- 2.2.2
install:
- travis_retry bundle install
sudo: false
cache: bundler

addons:
  code_climate:
    repo_token: bd0689fbbea3942f98293e557a67ab25be700ef489f28e680a74e3761b50c3fa

script:
- bundle exec rspec spec
